#include "ProjectSimulator/Project.h"
#include <fstream>
#include <iostream>
#include <sstream>
#include <filesystem>
#include <algorithm>

namespace ProjectSimulator {

Project::Project()
    : m_name("Untitled Project")
    , m_description("")
    , m_version("1.0.0")
    , m_author("")
    , m_path("")
    , m_mainFile("main.cpp")
    , m_valid(false) {
    m_lastModified = std::chrono::system_clock::now();
}

bool Project::LoadFromFile(const std::string& projectPath) {
    std::ifstream file(projectPath);
    if (!file.is_open()) {
        return false;
    }

    m_path = projectPath;
    m_valid = false;

    try {
        std::string line;
        while (std::getline(file, line)) {
            // Пропускаем комментарии и пустые строки
            if (line.empty() || line[0] == '#') {
                continue;
            }

            // Ищем знак равенства
            size_t pos = line.find('=');
            if (pos == std::string::npos) {
                continue;
            }

            std::string key = line.substr(0, pos);
            std::string value = line.substr(pos + 1);

            // Убираем пробелы
            key.erase(std::remove_if(key.begin(), key.end(), ::isspace), key.end());
            value.erase(std::remove_if(value.begin(), value.end(), ::isspace), value.end());

            // Парсим ключи
            if (key == "name") {
                m_name = value;
            } else if (key == "description") {
                m_description = value;
            } else if (key == "version") {
                m_version = value;
            } else if (key == "author") {
                m_author = value;
            } else if (key == "main_file") {
                m_mainFile = value;
            } else if (key == "asset") {
                m_assets.push_back(value);
            } else if (key == "dependency") {
                m_dependencies.push_back(value);
            } else {
                // Другие настройки
                m_settings[key] = value;
            }
        }

        file.close();
        m_valid = true;
        UpdateLastModified();
        return true;

    } catch (const std::exception& e) {
        std::cerr << "Error loading project: " << e.what() << std::endl;
        file.close();
        return false;
    }
}

bool Project::SaveToFile(const std::string& projectPath) const {
    std::ofstream file(projectPath);
    if (!file.is_open()) {
        return false;
    }

    try {
        file << "# Project Configuration File" << std::endl;
        file << "# Generated by Project Simulator" << std::endl;
        file << std::endl;

        file << "name=" << m_name << std::endl;
        file << "description=" << m_description << std::endl;
        file << "version=" << m_version << std::endl;
        file << "author=" << m_author << std::endl;
        file << "main_file=" << m_mainFile << std::endl;
        file << std::endl;

        // Ассеты
        for (const auto& asset : m_assets) {
            file << "asset=" << asset << std::endl;
        }
        file << std::endl;

        // Зависимости
        for (const auto& dependency : m_dependencies) {
            file << "dependency=" << dependency << std::endl;
        }
        file << std::endl;

        // Настройки
        for (const auto& setting : m_settings) {
            file << setting.first << "=" << setting.second << std::endl;
        }

        file.close();
        return true;

    } catch (const std::exception& e) {
        std::cerr << "Error saving project: " << e.what() << std::endl;
        file.close();
        return false;
    }
}

bool Project::LoadFromTemplate(const std::string& templatePath) {
    // Загружаем шаблон как обычный проект
    if (!LoadFromFile(templatePath)) {
        return false;
    }

    // Сбрасываем некоторые поля для нового проекта
    m_path = "";
    m_author = "";
    m_lastModified = std::chrono::system_clock::now();

    return true;
}

void Project::RemoveAsset(const std::string& asset) {
    auto it = std::find(m_assets.begin(), m_assets.end(), asset);
    if (it != m_assets.end()) {
        m_assets.erase(it);
    }
}

void Project::RemoveDependency(const std::string& dependency) {
    auto it = std::find(m_dependencies.begin(), m_dependencies.end(), dependency);
    if (it != m_dependencies.end()) {
        m_dependencies.erase(it);
    }
}

std::string Project::GetSetting(const std::string& key) const {
    auto it = m_settings.find(key);
    if (it != m_settings.end()) {
        return it->second;
    }
    return "";
}

std::string Project::GetMainFilePath() const {
    if (m_path.empty()) {
        return m_mainFile;
    }
    
    std::filesystem::path projectDir = std::filesystem::path(m_path).parent_path();
    return (projectDir / m_mainFile).string();
}

std::string Project::GetAssetPath(const std::string& asset) const {
    if (m_path.empty()) {
        return asset;
    }
    
    std::filesystem::path projectDir = std::filesystem::path(m_path).parent_path();
    return (projectDir / "assets" / asset).string();
}

bool Project::HasAsset(const std::string& asset) const {
    return std::find(m_assets.begin(), m_assets.end(), asset) != m_assets.end();
}

std::string Project::GetInfo() const {
    std::ostringstream oss;
    oss << "Project: " << m_name << std::endl;
    oss << "Version: " << m_version << std::endl;
    oss << "Author: " << m_author << std::endl;
    oss << "Description: " << m_description << std::endl;
    oss << "Main File: " << m_mainFile << std::endl;
    oss << "Assets: " << m_assets.size() << std::endl;
    oss << "Dependencies: " << m_dependencies.size() << std::endl;
    oss << "Valid: " << (m_valid ? "Yes" : "No") << std::endl;
    
    return oss.str();
}

} // namespace ProjectSimulator

